<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  version="1.0">

  <!-- Copyright 2002-2003 ConnectedMedia Corporation --> 

  <xsl:output method="html"/>

  <xsl:template match="/">

    <html>
      <body onload="DoLoad()">

        // Automatically Generated by Resources.xsl<br/>

        <xsl:apply-templates/>

        <br/>

      </body>
    </html>

  </xsl:template>

  <xsl:template match="resource">

    <xsl:value-of select="@cmd"/>
    <xsl:if test="@cmd = 'DATA'">
      "<xsl:value-of select="@type"/>"
    </xsl:if>
    ID
    <xsl:value-of select="@id"/>
    "<xsl:value-of select="@url"/>"
    <xsl:if test="@compress">
      <xsl:if test="@compress != 0">COMPRESS</xsl:if>
      <xsl:if test="@compress = 0">NOCOMPRESS</xsl:if>
    </xsl:if>
    <br/>

  </xsl:template>

  <xsl:template match="comment">
    <br/>
    // <xsl:value-of select="."/><br/>
    <br/>
  </xsl:template>

</xsl:stylesheet>
